// Mock com 12 seleções de grupos distintos para testes de terceiros colocados
export const MOCK_12_SELECOES_TERCEIROS: SelecaoResponse[] = [
  new SelecaoResponse({
    id: 101,
    nome: 'Equador',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Ecuador_national_football_team_logo.svg',
    pontuacaoSelecao: 4,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'ECU',
  }),
  new SelecaoResponse({
    id: 102,
    nome: 'Irã',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/ca/Flag_of_Iran.svg',
    pontuacaoSelecao: 3,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'IRN',
  }),
  new SelecaoResponse({
    id: 103,
    nome: 'México',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Mexico_national_football_team_logo_2021.png',
    pontuacaoSelecao: 4,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'MEX',
  }),
  new SelecaoResponse({
    id: 104,
    nome: 'Tunísia',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/ce/Tunisia_national_football_team_logo.svg',
    pontuacaoSelecao: 3,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'TUN',
  }),
  new SelecaoResponse({
    id: 105,
    nome: 'Alemanha',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/DFBEagle.svg',
    pontuacaoSelecao: 4,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'GER',
  }),
  new SelecaoResponse({
    id: 106,
    nome: 'Costa Rica',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Costa_Rica_national_football_team_logo.svg',
    pontuacaoSelecao: 3,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'CRC',
  }),
  new SelecaoResponse({
    id: 107,
    nome: 'Bélgica',
    logo: 'https://upload.wikimedia.org/wikipedia/en/6/62/Belgium_national_football_team_logo.svg',
    pontuacaoSelecao: 4,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'BEL',
  }),
  new SelecaoResponse({
    id: 108,
    nome: 'Sérvia',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/ff/Football_Association_of_Serbia_logo.svg',
    pontuacaoSelecao: 3,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'SRB',
  }),
  new SelecaoResponse({
    id: 109,
    nome: 'Uruguai',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/fe/Uruguay_national_football_team_logo.svg',
    pontuacaoSelecao: 4,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'URU',
  }),
  new SelecaoResponse({
    id: 110,
    nome: 'Camarões',
    logo: 'https://upload.wikimedia.org/wikipedia/en/4/4f/Cameroon_Football_Federation_logo.svg',
    pontuacaoSelecao: 3,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'CMR',
  }),
  new SelecaoResponse({
    id: 111,
    nome: 'Suíça',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f3/Switzerland_national_football_team_logo.png',
    pontuacaoSelecao: 4,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'SUI',
  }),
  new SelecaoResponse({
    id: 112,
    nome: 'Coreia do Sul',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/5c/South_Korea_national_football_team_logo.png',
    pontuacaoSelecao: 3,
    posicaoSelecaoFaseDeGrupos: 3,
    abreviacao: 'KOR',
  }),
];
import { SelecaoResponse } from "src/app/shared/models/responses/selecao.response";
import { SelecoesEliminatoriaResponse } from "./fase-eliminatoria-modal.component";

export const MOCK_SELECOES_ELIMINATORIA: SelecoesEliminatoriaResponse[] = [
  // Grupo A
  {
    IdGrupo: 'A',
    SelecaoResponse: new SelecaoResponse({
      id: 1,
      nome: 'Holanda',
      logo: 'https://upload.wikimedia.org/wikipedia/en/2/20/Netherlands_national_football_team_logo_2020.png',
      pontuacaoSelecao: 7,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'NED',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'A',
    SelecaoResponse: new SelecaoResponse({
      id: 2,
      nome: 'Senegal',
      logo: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Senegal_national_football_team_logo.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'SEN',
    }),
    PosicaoSelecaoSelecionada: 2,
  },
  {
    IdGrupo: 'A',
    SelecaoResponse: new SelecaoResponse({
      id: 95,
      nome: 'Uzbequistao',
      logo: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Senegal_national_football_team_logo.png',
      pontuacaoSelecao: 1,
      posicaoSelecaoFaseDeGrupos: 3,
      abreviacao: 'SEN',
    }),
    PosicaoSelecaoSelecionada: 3,
  },
  {
    IdGrupo: 'A',
    SelecaoResponse: new SelecaoResponse({
      id: 98,
      nome: 'Ubequistao',
      logo: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Senegal_national_football_team_logo.png',
      pontuacaoSelecao: 0,
      posicaoSelecaoFaseDeGrupos: 4,
      abreviacao: 'SEN',
    }),
    PosicaoSelecaoSelecionada: 4,
  },
  // Grupo B
  {
    IdGrupo: 'B',
    SelecaoResponse: new SelecaoResponse({
      id: 3,
      nome: 'Inglaterra',
      logo: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Three_Lions_crest.png',
      pontuacaoSelecao: 7,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'ENG',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'B',
    SelecaoResponse: new SelecaoResponse({
      id: 4,
      nome: 'Estados Unidos',
      logo: 'https://upload.wikimedia.org/wikipedia/en/e/e2/US_Soccer_Federation_logo_2016.png',
      pontuacaoSelecao: 5,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'USA',
    }),
    PosicaoSelecaoSelecionada: 2,
  },

  // Grupo C
  {
    IdGrupo: 'C',
    SelecaoResponse: new SelecaoResponse({
      id: 5,
      nome: 'Argentina',
      logo: 'https://upload.wikimedia.org/wikipedia/en/c/c1/Argentina_national_football_team_logo.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'ARG',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'C',
    SelecaoResponse: new SelecaoResponse({
      id: 6,
      nome: 'Polônia',
      logo: 'https://upload.wikimedia.org/wikipedia/en/1/12/Polish_Football_Association_logo.png',
      pontuacaoSelecao: 4,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'POL',
    }),
    PosicaoSelecaoSelecionada: 2,
  },

  // Grupo D
  {
    IdGrupo: 'D',
    SelecaoResponse: new SelecaoResponse({
      id: 7,
      nome: 'França',
      logo: 'https://upload.wikimedia.org/wikipedia/en/c/c3/France_national_football_team_seal.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'FRA',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'D',
    SelecaoResponse: new SelecaoResponse({
      id: 8,
      nome: 'Austrália',
      logo: 'https://upload.wikimedia.org/wikipedia/en/8/8f/Australia_national_football_team_logo.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'AUS',
    }),
    PosicaoSelecaoSelecionada: 2,
  },

  // Grupo E
  {
    IdGrupo: 'E',
    SelecaoResponse: new SelecaoResponse({
      id: 9,
      nome: 'Japão',
      logo: 'https://upload.wikimedia.org/wikipedia/en/0/09/Japan_national_football_team_logo.svg',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'JPN',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'E',
    SelecaoResponse: new SelecaoResponse({
      id: 10,
      nome: 'Espanha',
      logo: 'https://upload.wikimedia.org/wikipedia/en/3/3f/Spain_national_football_team_badge.png',
      pontuacaoSelecao: 4,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'ESP',
    }),
    PosicaoSelecaoSelecionada: 2,
  },

  // Grupo F
  {
    IdGrupo: 'F',
    SelecaoResponse: new SelecaoResponse({
      id: 11,
      nome: 'Marrocos',
      logo: 'https://upload.wikimedia.org/wikipedia/en/6/65/Royal_Moroccan_Football_Federation_logo.png',
      pontuacaoSelecao: 7,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'MAR',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'F',
    SelecaoResponse: new SelecaoResponse({
      id: 12,
      nome: 'Croácia',
      logo: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Croatian_Football_Federation_logo.png',
      pontuacaoSelecao: 5,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'CRO',
    }),
    PosicaoSelecaoSelecionada: 2,
  },

  // Grupo G
  {
    IdGrupo: 'G',
    SelecaoResponse: new SelecaoResponse({
      id: 13,
      nome: 'Brasil',
      logo: 'https://upload.wikimedia.org/wikipedia/en/0/05/Brazil_national_football_team_logo.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'BRA',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'G',
    SelecaoResponse: new SelecaoResponse({
      id: 14,
      nome: 'Suíça',
      logo: 'https://upload.wikimedia.org/wikipedia/en/f/f3/Switzerland_national_football_team_logo.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'SUI',
    }),
    PosicaoSelecaoSelecionada: 2,
  },

  // Grupo H
  {
    IdGrupo: 'H',
    SelecaoResponse: new SelecaoResponse({
      id: 15,
      nome: 'Portugal',
      logo: 'https://upload.wikimedia.org/wikipedia/en/5/5c/Portugal_national_football_team_logo.png',
      pontuacaoSelecao: 6,
      posicaoSelecaoFaseDeGrupos: 1,
      abreviacao: 'POR',
    }),
    PosicaoSelecaoSelecionada: 1,
  },
  {
    IdGrupo: 'H',
    SelecaoResponse: new SelecaoResponse({
      id: 16,
      nome: 'Coreia do Sul',
      logo: 'https://upload.wikimedia.org/wikipedia/en/5/5c/South_Korea_national_football_team_logo.png',
      pontuacaoSelecao: 4,
      posicaoSelecaoFaseDeGrupos: 2,
      abreviacao: 'KOR',
    }),
    PosicaoSelecaoSelecionada: 2,
  },
    {
    IdGrupo: 'I',
    SelecaoResponse: new SelecaoResponse({
        id: 17,
        nome: 'Alemanha',
        logo: 'https://upload.wikimedia.org/wikipedia/en/e/e0/DFBEagle.svg',
        pontuacaoSelecao: 6,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'GER',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'I',
    SelecaoResponse: new SelecaoResponse({
        id: 18,
        nome: 'Dinamarca',
        logo: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Danish_Football_Association_logo.svg',
        pontuacaoSelecao: 5,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'DEN',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
    {
    IdGrupo: 'J',
    SelecaoResponse: new SelecaoResponse({
        id: 21,
        nome: 'Itália',
        logo: 'https://upload.wikimedia.org/wikipedia/en/0/03/Italy_national_football_team_badge.png',
        pontuacaoSelecao: 7,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'ITA',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'J',
    SelecaoResponse: new SelecaoResponse({
        id: 22,
        nome: 'Suécia',
        logo: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Swedish_Football_Association_logo.svg',
        pontuacaoSelecao: 5,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'SWE',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
    {
    IdGrupo: 'K',
    SelecaoResponse: new SelecaoResponse({
        id: 25,
        nome: 'México',
        logo: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Mexico_national_football_team_logo_2021.png',
        pontuacaoSelecao: 6,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'MEX',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'K',
    SelecaoResponse: new SelecaoResponse({
        id: 26,
        nome: 'Ucrânia',
        logo: 'https://upload.wikimedia.org/wikipedia/en/5/5c/Ukrainian_Association_of_Football_logo.svg',
        pontuacaoSelecao: 5,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'UKR',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
    {
    IdGrupo: 'L',
    SelecaoResponse: new SelecaoResponse({
        id: 29,
        nome: 'Turquia',
        logo: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Turkish_Football_Federation_logo.svg',
        pontuacaoSelecao: 7,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'TUR',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'L',
    SelecaoResponse: new SelecaoResponse({
        id: 30,
        nome: 'República Tcheca',
        logo: 'https://upload.wikimedia.org/wikipedia/en/c/c1/Czech_Republic_national_football_team_logo.svg',
        pontuacaoSelecao: 5,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'CZE',
    }),
    PosicaoSelecaoSelecionada: 2,
    }, //crie mais 2 times para o grupo M
    {
    IdGrupo: 'M',
    SelecaoResponse: new SelecaoResponse({
        id: 33,
        nome: 'Bélgica',
        logo: 'https://upload.wikimedia.org/wikipedia/en/6/62/Belgium_national_football_team_logo.svg',
        pontuacaoSelecao: 7,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'BEL',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'M',
    SelecaoResponse: new SelecaoResponse({
        id: 34,
        nome: 'País de Gales',
        logo: 'https://upload.wikimedia.org/wikipedia/en/d/dc/Welsh_Football_Union_logo.svg',
        pontuacaoSelecao: 4,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'WAL',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
    {
    IdGrupo: 'N',
    SelecaoResponse: new SelecaoResponse({
        id: 37,
        nome: 'Tunísia',
        logo: 'https://upload.wikimedia.org/wikipedia/en/c/ce/Tunisia_national_football_team_logo.svg',
        pontuacaoSelecao: 6,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'TUN',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'N',
    SelecaoResponse: new SelecaoResponse({
        id: 38,
        nome: 'Canadá',
        logo: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Canada_soccer_logo.svg',
        pontuacaoSelecao: 4,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'CAN',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
    {
    IdGrupo: 'O',
    SelecaoResponse: new SelecaoResponse({
        id: 39,
        nome: 'Camarões',
        logo: 'https://upload.wikimedia.org/wikipedia/en/4/4f/Cameroon_Football_Federation_logo.svg',
        pontuacaoSelecao: 6,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'CMR',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'O',
    SelecaoResponse: new SelecaoResponse({
        id: 40,
        nome: 'Sérvia',
        logo: 'https://upload.wikimedia.org/wikipedia/en/f/ff/Football_Association_of_Serbia_logo.svg',
        pontuacaoSelecao: 5,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'SRB',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
    {
    IdGrupo: 'P',
    SelecaoResponse: new SelecaoResponse({
        id: 41,
        nome: 'Gana',
        logo: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Ghana_Football_Association_logo.svg',
        pontuacaoSelecao: 6,
        posicaoSelecaoFaseDeGrupos: 1,
        abreviacao: 'GHA',
    }),
    PosicaoSelecaoSelecionada: 1,
    },
    {
    IdGrupo: 'P',
    SelecaoResponse: new SelecaoResponse({
        id: 42,
        nome: 'Uruguai',
        logo: 'https://upload.wikimedia.org/wikipedia/en/f/fe/Uruguay_national_football_team_logo.svg',
        pontuacaoSelecao: 4,
        posicaoSelecaoFaseDeGrupos: 2,
        abreviacao: 'URU',
    }),
    PosicaoSelecaoSelecionada: 2,
    },
];
